name: squidgame
description: "A game store app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_triple: ^1.2.5
  font_awesome_flutter: ^9.2.0
  google_fonts: ^6.2.1
  iconly: ^1.0.1
  get_it: ^8.0.1
  injectable: ^2.5.0
  device_frame: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
